# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AmqpPublish < Formula
  desc "A command-line tool for publishing messages to a RabbitMQ server"
  homepage "https://github.com/yasithab/amqp-publish"
  version "1.0.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yasithab/amqp-publish/releases/download/1.0.0/amqp-publish_Darwin_x86_64.tar.gz"
      sha256 "f66e3ac1bee1a0680114ed4ced5c0d2fd192fe29a868b1536656dae219e93b89"

      def install
        bin.install "amqp-publish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yasithab/amqp-publish/releases/download/1.0.0/amqp-publish_Darwin_arm64.tar.gz"
      sha256 "ce338e465ebb1a21060d0e37f392a06f6904a01b6d1ce1e37e977a539981c540"

      def install
        bin.install "amqp-publish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/amqp-publish/releases/download/1.0.0/amqp-publish_Linux_x86_64.tar.gz"
        sha256 "be05324ba74ced886ac99b8ec84ddf67efaa300e14da0f004eb45882e3e4890c"

        def install
          bin.install "amqp-publish"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/yasithab/amqp-publish/releases/download/1.0.0/amqp-publish_Linux_arm64.tar.gz"
        sha256 "ce0f6beeea489114734c97aa723758e3e1bb85417c28cb3d6cb428977c148193"

        def install
          bin.install "amqp-publish"
        end
      end
    end
  end

  test do
    system "#{bin}/amqp-publish --version"
  end
end
